# Generated by Django 5.2.6 on 2025-10-01 12:54

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(help_text='Enter a project name', max_length=50, unique=True)),
                ('description', models.TextField(help_text='Describe the project', max_length=500)),
                ('picture', models.ImageField(default='project_images/loading.jpg', upload_to='project_images/')),
            ],
            options={
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('project_name'), name='project_unique_name_constraint', violation_error_message='project already exists')],
            },
        ),
    ]
