# Generated by Django 5.2.6 on 2025-10-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_site', '0002_alter_project_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='picture',
            field=models.ImageField(default='project_images/loading.jpg', upload_to='project_images/'),
        ),
    ]
